import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import "@/styles/global.css";

/*
Common Dashboard Layout:

body (flex flex-col)
├── header
└── content (flex flex-1)
    ├── sidebar (fixed width)
    └── main (flex-1)
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head />
      <body className="min-h-screen flex flex-col bg-green-200">
        {/*==== HEADER ==== */}

        <header
          className="bg-red-500
                      m-2 p-1"
        >
          Header
        </header>

        {/*==== CONTENT ==== */}

        <div className="flex flex-1">
          {/*==== NAVIGATION ==== */}
          <div
            className="w-[200px] bg-green-500
                      bg-gray-500 m-4 p-2"
          >
            <Navigation />
          </div>

          {/*==== MAIN ==== */}
          <main
            className="flex-1
                      bg-blue-500 m-4 p-2"
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
